Repository visionITssu/visionITssu_2024, pull requests merged in 2024-11, with the labels that each got.

#29 [#28] 빠진 파일 추가 및 소켓 코드 수정
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/app.service.ts
  apps/server/src/main.ts
  apps/server/src/photo-edit/photo-edit.controller.ts
  apps/server/src/photo-edit/photo-edit.module.ts
  apps/server/src/photo-verification/photo-verification.module.ts
  apps/server/src/photo-verification/photo-verification.service.ts
  apps/server/src/socket/index.html
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.js
  apps/server/src/socket/socket.module.ts
  apps/server/src/socket/socket.service.ts
  package-lock.json
  turbo.json
Labels: feat, fix

#36 Feat/#32
  apps/client/package.json
  apps/client/src/pages/WebcamPage.tsx
  package-lock.json
  package.json
Labels: feat

#38 [#37] GuidePage 설명 내용 수정 및 버튼 재배치
  apps/client/src/pages/GuidePage.tsx
Labels: style

#40 Style/#39
  apps/client/package.json
  apps/client/src/index.css
  apps/client/src/pages/GuidePage.tsx
  apps/client/src/pages/LandingPage.tsx
  apps/client/src/pages/WebcamPage.tsx
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/app.service.ts
  apps/server/src/main.ts
  apps/server/src/photo-edit/photo-edit.controller.ts
  apps/server/src/photo-edit/photo-edit.module.ts
  apps/server/src/photo-verification/photo-verification.module.ts
  apps/server/src/photo-verification/photo-verification.service.ts
  apps/server/src/socket/index.html
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.js
  apps/server/src/socket/socket.module.ts
  apps/server/src/socket/socket.service.ts
  build.sh
  package-lock.json
  package.json
  turbo.json
Labels: style

#47 [#46] WebcamPage 에 server 와 Socket.IO 연결
  apps/client/src/pages/WebcamPage.tsx
Labels: feat

#49 [#48] GuidePage 안내 문구 수정 및 버튼 재배치
  apps/client/src/pages/GuidePage.tsx
Labels: style

#53 [#50] ui/buttion 및 메인 색 리팩토링
  apps/client/src/App.tsx
  apps/client/src/pages/ConfirmPage.tsx
  apps/client/src/pages/GuidePage.tsx
  apps/client/src/pages/LandingPage.tsx
  apps/client/src/pages/WebcamPage.tsx
  apps/client/src/style/styled.d.ts
  apps/client/src/style/theme.ts
  package-lock.json
  packages/ui/package.json
  packages/ui/src/button.tsx
Labels: refactor
